name:                newtype
version:             0.1.0.0
github:              "dkendal/newtype"
license:             BSD3
author:              "Dylan Kendal"
maintainer:          "dylankendal@gmail.com"
copyright:           "2022 Dylan Kendal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dkendal/newtype#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  newtype-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - newtype

tests:
  newtype-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - newtype
