name: newtype
version: 0.1.0.0
homepage: https://github.com/dkendal/newtype#readme
license: BSD3
license-file: LICENSE
author: Dylan Kendal
maintainer: dylankendal@gmail.com
copyright: 2022 Dylan Kendal
category: Data
build-type: Simple
cabal-version: ">=1.10"
extra-source-files: README.md

dependencies:
  - base >= 4.7 && < 5
  - parsec

executable:
  name: nt
  ghc-options: -Wall
  source-dirs: src
  main: Main.hs
  default-language: Haskell2010
