# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  test:
    cmds:
      - cargo test
    silent: true
    sources:
      - ./src/**/*.rs
      - ./src/**/*.pest
      - ./Cargo.lock
      - ./Cargo.toml
