[package]
name = "newtype-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
name = "newtype_macros_lib"
path = "src/lib.rs"

[dependencies]
proc-macro2 = "*"
quote = "*"
syn = { version = "*", features = ["extra-traits", "visit"] }
